# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='nno',
            field=models.IntegerField(),
        ),
    ]
